### PR TITLE
gis: fix user warning when testing geo schelling example

### PR DESCRIPTION
**Pull request by wang-boyu**
As part of https://github.com/projectmesa/mesa-examples/issues/172.

### CODE REVIEW

**Comment by wang-boyu** [comment]
pre-commit.ci autofix

**Comment by EwoutH** [comment]
Thanks! Could you explain briefly what the warning was and this fixes it?

**Comment by wang-boyu** [comment]
Sure! Sorry that I didn't provide more info.

Basically the raw data contains a set of polygons, and we want to create a graph out of it, where a node represents a polygon, and a link between two polygons means that they are touch neighbors (or in other words, adjacent polygons).

But the polygons in our data can be divided into several groups, and there's no link in-between these groups. I simply keep the largest group for the model.

In `server.py` we hardcoded the `view` and `zoom` parameters to be `[52, 12]` and `4` to zoom into these regions and ignored other regions. Now that we removed other regions, these parameters aren't needed any longer.

Alternatively, we could set `silence_warning` to `True` (links: [here](https://pysal.org/libpysal/generated/libpysal.weights.W.html) and [here](https://pysal.org/libpysal/generated/libpysal.weights.Queen.html#libpysal.weights.Queen.from_iterable)) in Mesa-Geo: https://github.com/projectmesa/mesa-geo/blob/5fb2dde5e63bbfea10775af988848dbfde4ce8a2/mesa_geo/geospace.py#L297. This will silence all warnings for everyone, but I think keeping it may be useful. Hence I fixed it only for the test case of this example.

**Comment by EwoutH** [comment]
Awesome! Could you rebase/update this PR? If correct, this is the one that will turn it green!

If you find the current warnings settings too strict for Mesa-geo, we could also remove the `-Werror` or allow some more warnings to pass.

**Review by EwoutH — APPROVED** [review]

**Comment by wang-boyu** [comment]
pre-commit.ci autofix

**Comment by wang-boyu** [comment]
Rebased!

We can probably keep the current warning settings for now and decide later: )

**Comment by wang-boyu** [comment]
Need to rush to a meeting and will check this later

**Comment by EwoutH** [comment]
Green!!!

Awesome.

**Comment by wang-boyu** [comment]
Fixed pre-commit error and squashed all commits into one.

**Comment by EwoutH** [comment]
Go ahead, I approved already

**Comment by wang-boyu** [comment]
Thanks @EwoutH

**Pull request merged**
