### PR TITLE
Add a 'headless' option to run.py to allow wolf_sheep to run headless

### PR DESCRIPTION
**Pull request by smubita**
An example of how to modify an existing example (wolf_sheep) to include an optional headless option. This is related to the discussion topic here: [https://github.com/projectmesa/mesa/discussions/1645](https://github.com/projectmesa/mesa/discussions/1645)

### CODE REVIEW

**Comment by jackiekazil** [comment]
@smubita - we added the pre-commit.ci to fix the build issue. Can you update your branch from main, then re-push. The build should be fixed after that.

**Comment by smubita** [comment]
Hi, @jackiekazil . I pulled from main the original repo. I also made changes according to the maintainer's remarks in the issue I opened, and copied the change to most of the examples in the repo.

**Comment by jackiekazil** [comment]
I am okay with this, but this to me is a more impactful change & @rht has commented on other threads related to this, so I want to let him chim in before merging.

**Comment by rht** [comment]
I agree with the changes. :)

**Comment by jackiekazil** [comment]
LGTM! Thank you for the contribution!

**Pull request merged**
