### PR TITLE
Fix issue #2191:I have moved the examples files from https://github.c…

### PR DESCRIPTION
**Pull request by VinayakPaka**
I have moved the examples files from mesa to mesa-examples. 

If u need anything else to update. Drop a message I will solve that.

### CODE REVIEW

**Comment by EwoutH** [comment]
Thanks for the PR. I clearly should have described the issue better.

I'm going to give @jayash1973 with #152 the initiative for a week or so, so putting this PR on hold for that time.

**Comment by jayash1973** [comment]
hey @EwoutH is there any other place where the discussions take place for Mesa?

**Comment by jayash1973** [comment]
@EwoutH there are some errors in the current code in the https://github.com/projectmesa/mesa/tree/main/mesa/experimental/devs/examples

should i fix them and also add solara visualization to them all in one file insted of 3 files like agents.py, app.py and model.py like i did before. after the changes are made shold we copy and transfer them after that? how does that sound?

**Comment by EwoutH** [comment]
> is there any other place where the discussions take place for Mesa?

Yes, two places:
- On Matrix: https://matrix.to/#/#project-mesa:matrix.org
- On GitHub discussions: https://github.com/projectmesa/mesa/discussions

**Comment by EwoutH** [comment]
@VinayakPaka if you want to move forward with this PR go ahead. Try to make [atomic commits](https://www.pauline-vos.nl/atomic-commits/) for each step in the process.

To manage expectations, I don't have much time to review, so try to follow https://github.com/projectmesa/mesa/issues/2191 as closely as possible. @jayash1973 has done some work on Readme's and the visualisation, maybe he will allow you to use those.

**Comment by EwoutH** [comment]
Closing for now due to lack of progress.

**Pull request closed without merging**
