### PR TITLE
gis: update three examples to use solara viz

### PR DESCRIPTION
**Pull request by wang-boyu**
This PR updates the remaining three gis examples to use Solara viz, partly addressing https://github.com/projectmesa/mesa-examples/issues/154. It depends on https://github.com/projectmesa/mesa-geo/pull/254 to be released, as these examples use raster layers.

Also made some small adjustments in ordering components to account for the grid layout, instead of the previous column layout in Solara viz.

Failed tests in agents_and_networks example should be fixed by https://github.com/projectmesa/mesa/pull/2368.

### CODE REVIEW

**Review by EwoutH — APPROVED** [review]
Awesome! Thanks voor working on this!

> It depends on https://github.com/projectmesa/mesa-geo/pull/254 to be released

I think we can release a new pre-release right now, right? Do you need any help with that?

**Comment by wang-boyu** [comment]
Yes! A new pre-release would be great. Would you like to make one? Or else I could find some time to do it too.

**Comment by EwoutH** [comment]
I published v0.9.0 alpha 1: https://github.com/projectmesa/mesa-geo/releases/tag/v0.9.0a1

**Comment by wang-boyu** [comment]
Thanks @EwoutH! Appreciate it. This PR is ready now.

**Pull request merged**
